before:
  hooks:
    - go mod tidy
    - go mod download
    - yarn --cwd web --force install
    - yarn --cwd web run build

builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X "main.version={{.Version}}"
      - -X "main.gitCommit={{.ShortCommit}}"
      - -X "main.buildDate={{.Now.Format "2006-01-02"}}"
    main: ./cmd/main.go
    binary: lime

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}'
    files:
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: '{{ .Tag }}-next'

upx:
  - enabled: false

changelog:
  sort: asc
  filters:
    exclude:
      - init
      - '^.*?ci:'
      - '^.*?test:'
      - '^.*?build(deps):'
      - '^.*?build:'
      - 'README'
      - 'Up'
      - 'merge conflict'
      - Bump
      - Small fix
      - Update
      - Updating
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: 'Security updates'
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 150
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: 'Documentation updates'
      regexp: ^.*?doc(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: 'Build process updates'
      regexp: ^.*?build(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999

dockers:
  - image_templates:
      - 'werbot/lime:v{{ .Version }}-amd64'
      - 'ghcr.io/werbot/lime:v{{ .Version }}-amd64'
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - '--pull'
      - '--label=io.artifacthub.package.readme-url=https://raw.githubusercontent.com/werbot/lime/main/README.md'
      - '--label=io.artifacthub.package.maintainers=[{"name":"Werbot inc."}]'
      - '--label=io.artifacthub.package.license=MIT'
      - '--label=org.opencontainers.image.description=🍋 Very light license-key server in 1 file'
      - '--label=org.opencontainers.image.created={{.Date}}'
      - '--label=org.opencontainers.image.name={{.ProjectName}}'
      - '--label=org.opencontainers.image.revision={{.FullCommit}}'
      - '--label=org.opencontainers.image.version={{.Version}}'
      - '--label=org.opencontainers.image.source={{.GitURL}}'
      - '--platform=linux/amd64'
    goarch: amd64

  - image_templates:
      - 'werbot/lime:v{{ .Version }}-arm64'
      - 'ghcr.io/werbot/lime:v{{ .Version }}-arm64'
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - '--pull'
      - '--label=io.artifacthub.package.readme-url=https://raw.githubusercontent.com/werbot/lime/main/README.md'
      - '--label=io.artifacthub.package.maintainers=[{"name":"Werbot inc."}]'
      - '--label=io.artifacthub.package.license=MIT'
      - '--label=org.opencontainers.image.description=🍋 Very light license-key server in 1 file'
      - '--label=org.opencontainers.image.created={{.Date}}'
      - '--label=org.opencontainers.image.name={{.ProjectName}}'
      - '--label=org.opencontainers.image.revision={{.FullCommit}}'
      - '--label=org.opencontainers.image.version={{.Version}}'
      - '--label=org.opencontainers.image.source={{.GitURL}}'
      - '--platform=linux/arm64'
    goarch: arm64

docker_manifests:
  - name_template: 'werbot/lime:v{{ .Version }}'
    image_templates:
      - 'werbot/lime:v{{ .Version }}-amd64'
      - 'werbot/lime:v{{ .Version }}-arm64'
  - name_template: 'ghcr.io/werbot/lime:v{{ .Version }}'
    image_templates:
      - 'ghcr.io/werbot/lime:v{{ .Version }}-amd64'
      - 'ghcr.io/werbot/lime:v{{ .Version }}-arm64'
  - name_template: 'werbot/lime:latest'
    image_templates:
      - 'werbot/lime:v{{ .Version }}-amd64'
      - 'werbot/lime:v{{ .Version }}-arm64'
  - name_template: 'ghcr.io/werbot/lime:latest'
    image_templates:
      - 'ghcr.io/werbot/lime:v{{ .Version }}-amd64'
      - 'ghcr.io/werbot/lime:v{{ .Version }}-arm64'