name: "\U0001F680 Feature Request"
title: "\U0001F680 [Feature]: "
description: Suggest an idea to improve this project.
labels: ["✏️ Feature"]

body:
  - type: markdown
    id: notice
    attributes:
      value: |
        ### Notice
        - If you think this is just a bug, open the issue with the **☢️ Bug Report** template.
        - Write your issue with clear and understandable English.
  - type: textarea
    id: description
    attributes:
      label: "Feature Description"
      description: "A clear and detailed description of the feature you would like to see added."
      placeholder: "Explain your feature clearly, and in detail."
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context (optional)"
      description: "If you have something else to describe, write them here."
      placeholder: "Write here what you can describe differently."
  - type: textarea
    id: snippet
    attributes:
      label: "Code Snippet (optional)"
      description: "Code snippet may be really helpful to describe some features."
      placeholder: "Share a code snippet to explain the feature better."
      render: go
      value: |
        package main

        import "fmt"

        func main() {
          fmt.Print("hello word")
        }
  - type: checkboxes
    id: terms
    attributes:
      label: "Checklist:"
      description: "By submitting this issue, you confirm that:"
      options:
        - label: "I agree to follow lime's [Code of Conduct](https://github.com/werbot/lime/blob/master/.github/CODE_OF_CONDUCT.md)."
          required: true
        - label: "I have checked for existing issues that describe my suggestion prior to opening this one."
          required: true
        - label: "I understand that improperly formatted feature requests may be closed without explanation."
          required: true